import React from "react";
import Wrap from "../components/wrap";
import { SiDiscord } from "react-icons/si";
import { useRef, useEffect } from "react";
import { getDiscordURL } from "../static/util";
import Image from "next/image";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export default () => {
  const container = useRef(null);

  useEffect(() => {
    (async () => {
      await sleep(1);
      container?.current?.childNodes[0]?.classList?.remove("opacity-0", "-translate-y-8");
    })();
  }, [container]);

  const imgs = [
    "https://i.pravatar.cc/150?img=33",
    "https://i.pravatar.cc/150?img=15",
    "https://i.pravatar.cc/150?img=62",
    "https://i.pravatar.cc/150?img=69",
    "https://i.pravatar.cc/150?img=35",
    "https://i.pravatar.cc/150?img=56",
    "https://i.pravatar.cc/150?img=12",
    "https://i.pravatar.cc/150?img=8",
    "https://i.pravatar.cc/150?img=25",
    "https://i.pravatar.cc/150?img=11",
  ];

  return (
    <>
      <div className="flex items-center justify-center pt-20" ref={container}>
        <div className="flex flex-col justify-between p-5 duration-300 -translate-y-8 border rounded-lg shadow-md opacity-0 border-main-border bg-main-800">
          <div className="min-w-[400px] max-w-[400px]">
            <div className="flex max-w-max gap-0.5">
              <div className="flex items-center py-0.5 mb-auto max-h-max">
                <div className="flex items-center justify-center -space-x-3">
                  <span className="block w-6 h-6 border-2 rounded-full border-main-800 bg-main-300" />
                  <span className="block w-8 h-8 border-4 rounded-full border-main-800 bg-main-500" />
                </div>
                <h1 className="">Welcome to Tavern!</h1>
              </div>
            </div>

            <p className="mt-2 text-xs text-main-text/70">
              Tavern is a community based storytelling and creative platform for all digital art forms.
            </p>
            <div className="min-w-[400px]  max-w-[400px] mt-2.5">
              <p className="text-xs text-main-text/70">
                Join these and 500+ other digital creatives and embark on your creative storytelling journey.
              </p>
              <div className="relative flex items-center mt-2.5">
                {imgs.map((_, index) => (
                  <Image
                    className={`-mx-1.5 rounded-full border-2 border-main-700 shadow-md`}
                    height="36"
                    width="36"
                    quality={100}
                    src={_}
                    alt="discord user profile picture generated by api"
                  />
                ))}
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-5 min-w-[400px]  max-w-[400px]">
            <p className="mt-3 text-xs text-main-text/70">
              By loging-in or sigin-up you agree to our{" "}
              <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-main-text hover:decoration-white">
                Terms of Service
              </a>{" "}
              and{" "}
              <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-main-text hover:decoration-white">
                Privacy Policy
              </a>{" "}
              including{" "}
              <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-main-text hover:decoration-white">
                Cookie Use
              </a>
            </p>
            <a
              href={getDiscordURL()}
              className="flex-1 px-4 min-h-[38px] gap-2 text-sm relative text-main-text/70 border rounded-md bg-main-700 border-main-border  hover:border-white/70  duration-150 flex items-center justify-center"
            >
              Continue with Discord
              <SiDiscord size={18} />
            </a>
            <span className="relative flex items-center w-full gap-2 text-xs text-center">
              <span className="h-[1px] block flex-1 bg-main-border" />
              <span className="duration-150 hover:cursor-pointer opacity-70 hover:opacity-100">Need help?</span>
              <span className="h-[1px] block flex-1 bg-main-border" />
            </span>
          </div>
        </div>
      </div>
    </>
  );
};
