import { getDiscordURL } from "../static/util";
import { fetchTokens, fetchUserDetails } from "../static/api";
import { useEffect, useState } from "react";
import Image from "next/image";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    if (user === null) {
      (async () => await fetchUserDetails(setUser))();
    }
  }, [user]);

  console.log(user);

  return (
    <div className="w-full max-w-5xl mx-auto mt-20">
      {!user && <a href={getDiscordURL()}>Login with Discord</a>}
      <br /> <br />
      {user && (
        <div>
          currently logged in as:
          <Image
            className="rounded-full"
            height="50"
            width="50"
            src={`https://cdn.discordapp.com/avatars/${user.data.id}/${user.data.avatar}.png`}
            alt="discord user profile picture generated by api"
          />
          {}
          <h1>
            {user.data.username}#{user.data.discriminator}
          </h1>
        </div>
      )}
      {/* <h1>{user?.data?.username}</h1> */}
    </div>
  );
}
