import { getDiscordURL } from "../static/util";
import { fetchUserDetails, handleLogout } from "../static/api";
import { useEffect, useState } from "react";
import Image from "next/image";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    if (user === null) {
      (async () => await fetchUserDetails(setUser))();
    }
  }, [user]);

  return (
    <div className="w-full max-w-5xl mx-auto mt-20">
      {!user && <a href={getDiscordURL()}>Login with Discord</a>}
      <br /> <br />
      {user && (
        <div>
          <button onClick={() => handleLogout(setUser)}>LOGOUT OF ACCOUNT</button>
          <br /> <br />
          <Image
            className="rounded-full"
            height="75"
            width="75"
            src={`https://cdn.discordapp.com/avatars/${user.me.id}/${user.me.avatar}.png`}
            alt="discord user profile picture generated by api"
          />
          <br />
          <h1>
            {user.me.username}#{user.me.discriminator}
          </h1>
          <br /> <br />
          your account connections:
          <ul>
            {user.connections.map((connection, index) => (
              <li key={index}>
                {connection.type}: {connection.name}
              </li>
            ))}
          </ul>
          <br /> <br />
          your current discord servers:
          <ul>
            {user.guilds.map((guild, index) => (
              <li key={index}>{guild.name}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
