import Image from "next/image";
import { getDiscordURL } from "../static/util";
import { SiDiscord } from "react-icons/si";

export default () => {
  return (
    <>
      <nav className="flex items-center justify-center max-w-xl mx-auto mt-20">
        <div className="flex items-center gap-2.5">
          <div className="flex items-center justify-center -space-x-3">
            <span className="block w-6 h-6 border-2 rounded-full border-main-900 bg-main-300" />
            <span className="block w-8 h-8 border-4 rounded-full border-main-900 bg-main-500" />
          </div>
          <h1 className="font-medium tracking-wide">Tavern</h1>
        </div>
        <ul className="flex items-center gap-5 ml-auto text-white/70">
          <li className="text-sm font-normal leading-5 text-white/70">
            What is Tavern?
          </li>
          <li className="text-sm font-normal leading-5 text-white/70">Features</li>
          <li className="text-sm font-normal leading-5 text-white/70">Pricing</li>
        </ul>
      </nav>
      <main className="flex flex-col items-center max-w-2xl gap-5 mx-auto text-center mt-28">
        <h1 className="text-4xl font-semibold leading-snug tracking-normal ">
          All-In-One collaberation and discovery tool for digital creatives.
        </h1>

        <p className="max-w-md text-sm font-normal leading-5 text-white/70">
          Tavern is a discovery and collaberation tool for digital storytelling. Our
          community turns art into a meaningful stories. Join these and our growing
          community of 500+ other members and embark on your creative storytelling
          journey.
        </p>

        <div className="relative flex items-center -space-x-3">
          {[...Array(10)].map((_, i) => (
            <Image
              key={i}
              className={`rounded-full border-[3px] border-main-900`}
              height="36"
              width="36"
              quality={100}
              src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
              alt="discord user profile picture generated by api"
            />
          ))}
        </div>

        <p className="max-w-max tracking-wide text-[12px] text-white/70">
          By continuing you agree to our{" "}
          <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-white hover:decoration-white">
            Terms of Service
          </a>{" "}
          and{" "}
          <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-white hover:decoration-white">
            Privacy Policy
          </a>{" "}
        </p>
        <a
          href={getDiscordURL()}
          className="max-w-max flex-1 px-6 min-h-[38px] gap-2 text-sm relative text-white/70 border rounded-md bg-main-800 border-main-border  hover:border-white/70  duration-150 flex items-center justify-center"
        >
          Continue with Discord
          <SiDiscord size={18} />
        </a>
      </main>
    </>
  );
};
