import Image from "next/image";
import { getDiscordURL } from "../static/util";
import { SiDiscord } from "react-icons/si";
import { useWindowScroll } from "../hooks/useWinScroll";

export default () => {
  return (
    <>
      <Navbar />
      <main className="flex flex-col items-center max-w-2xl gap-5 mx-auto text-center mt-44">
        <h1 className="text-4xl font-semibold leading-snug tracking-normal ">
          All-In-One collaberation and discovery tool for digital creatives.
        </h1>

        <p className="max-w-md text-sm font-normal leading-5 text-white/70">
          Tavern is a discovery and collaberation tool for digital storytelling. Our
          community turns art into a meaningful stories. Join these and our growing
          community of 500+ other members and embark on your creative storytelling
          journey.
        </p>

        <div className="flex items-center -space-x-3">
          {[...Array(10)].map((_, i) => (
            <Image
              key={i}
              className={`rounded-full border-[3px] border-main-900`}
              height="36"
              width="36"
              quality={100}
              src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
              alt="discord user profile picture generated by api"
            />
          ))}
        </div>

        <p className="max-w-max tracking-wide text-[12px] text-white/70">
          By continuing you agree to our{" "}
          <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-white hover:decoration-white">
            Terms of Service
          </a>{" "}
          and{" "}
          <a className="underline duration-150 decoration-white/40 underline-offset-2 hover:cursor-pointer hover:text-white hover:decoration-white">
            Privacy Policy
          </a>{" "}
        </p>
        <a
          href={getDiscordURL()}
          className="max-w-max flex-1 px-6 min-h-[38px] gap-2 text-sm text-white/70 border rounded-md bg-main-800 border-main-border  hover:border-white/70  duration-150 flex items-center justify-center"
        >
          Continue with Discord
          <SiDiscord size={18} />
        </a>
      </main>
      <section className="relative mt-24 pb-28 -z-10">
        <div className="max-w-4xl mx-auto blur-[0.01rem]">
          <Image
            src={`/landing.png`}
            className="object-contain !w-full !relative -z-10 !h-['unset'] block  max-w-full align-middle border rounded-xl drop-shadow-md bg-main-800 border-main-border"
            fill
            quality={100}
          />
        </div>
      </section>

      <section className="flex flex-col items-center gap-5 mx-auto text-center mb-28">
        <h1 className="max-w-2xl text-4xl font-semibold leading-snug tracking-normal ">
          Flexible pricing as you scale
        </h1>

        <p className="max-w-md text-sm font-normal leading-5 text-white/70">
          Industry standard social medias do not value the digital creative. Art is
          storytelling and we have a mission to your tale by rewarding creators and
          collaberatiors.
        </p>

        <div className="grid w-full max-w-4xl grid-cols-3 gap-5 mt-1.5">
          <div className="border border-main-border rounded-lg min-h-[400px] py-3.5">
            <div className="grid gap-0.5 pb-5">
              <h1 className="font-medium tracking-wide">Free</h1>
              <p className="max-w-md px-5 text-sm font-normal leading-5 text-white/70">
                Hobbyist
              </p>
              <h2 className="max-w-2xl text-4xl font-semibold leading-snug tracking-normal ">
                $0
              </h2>

              <span className="relative flex items-center w-full gap-2 text-xs tracking-wide text-center">
                <span className="h-[1px] block flex-1 bg-main-border" />
                <span className="text-sm text-white/70">Forever</span>
                <span className="h-[1px] block flex-1 bg-main-border" />
              </span>
            </div>
          </div>
          <div className="border-4 border-[#f0c165] rounded-lg min-h-[400px] py-3.5 relative">
            <span className="block absolute left-3 -top-3 bg-[#f0c165] rounded-md">
              <p className="px-3 py-0.5 text-sm leading-5 font-medium tracking-wide">
                Best Value
              </p>
            </span>
            <div className="grid gap-0.5">
              <h1 className="font-medium tracking-wide">Lite</h1>
              <p className="max-w-md px-5 text-sm font-normal leading-5 text-white/70">
                Supporter
              </p>
              <h2 className="max-w-2xl text-4xl font-semibold leading-snug tracking-normal ">
                $5
              </h2>
              <span className="relative flex items-center w-full gap-2 text-xs tracking-wide text-center">
                <span className="h-[1px] block flex-1 bg-main-border" />
                <span className="text-sm text-white/70">Billed Monthly</span>
                <span className="h-[1px] block flex-1 bg-main-border" />
              </span>
            </div>
          </div>
          <div className="border border-main-border rounded-lg min-h-[400px] py-3.5">
            <div className="grid gap-0.5">
              <h1 className="font-medium tracking-wide">Pro</h1>
              <p className="max-w-md px-5 text-sm font-normal leading-5 text-white/70">
                Super-Supporter
              </p>
              <h2 className="max-w-2xl text-4xl font-semibold leading-snug tracking-normal ">
                $12
              </h2>
              <span className="relative flex items-center w-full gap-2 text-xs tracking-wide text-center">
                <span className="h-[1px] block flex-1 bg-main-border" />
                <span className="text-sm text-white/70">Billed Monthly</span>
                <span className="h-[1px] block flex-1 bg-main-border" />
              </span>
            </div>
          </div>
        </div>

        {/* <div className="grid w-full max-w-4xl grid-cols-1 gap-5 mx-auto mt-1.5">
          <div className="flex flex-row-reverse gap-5">
            <div className="flex-1 p-5 overflow-hidden border rounded-xl border-main-border">
              <h1 className="font-medium tracking-wide  mb-1.5">Authentication</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                For your security and online safety — we offer easy authentication
                via Discord.
              </p>
            </div>
            <div className="flex-1 p-5 overflow-hidden border rounded-xl border-main-border">
              <h1 className="font-medium tracking-wide  mb-1.5">Full Control</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                Accept or Deny suggested collaberations anonymously or even just
                disable it.
              </p>
            </div>
            <div className="p-5 border rounded-xl border-main-border flex-[1.35]">
              <h1 className="font-medium tracking-wide  mb-1.5">No Advertisement</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                An ad-free experience is critical for building an immersive Tavern
                whereby each member can truly get lost in fantasy.
              </p>
            </div>
          </div>
          <div className="flex gap-5">
            <div className="flex-1 p-5 overflow-hidden border rounded-xl border-main-border">
              <h1 className="font-medium tracking-wide  mb-1.5">Your Tavern</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                Save your favourite threads for later with ease by simply giving it a
                like.
              </p>
            </div>
            <div className="flex-1 p-5 overflow-hidden border rounded-xl border-main-border">
              <h1 className="font-medium tracking-wide  mb-1.5">Collaberations</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                Seamless collaberation, no hastle meaningful tales together.
              </p>
            </div>
            <div className="p-5 border rounded-xl border-main-border flex-[1.5]">
              <h1 className="font-medium tracking-wide  mb-1.5">Crediting</h1>
              <p className="max-w-md text-sm font-normal leading-5 text-white/70">
                Each thread will respectively reward each collaberator by displaying
                their profiles on the collaberation timeline.
              </p>
            </div>
          </div>
        </div> */}
      </section>

      <Footer />
    </>
  );
};

const Navbar = () => {
  const isAtTop = useWindowScroll();
  return (
    <nav
      className={`flex items-center justify-center  mx-auto z-100
      fixed left-0 right-0  duration-200  rounded-full py-1 px-3 mt-5
     ${
       isAtTop
         ? "bg-transparent top-8  max-w-4xl"
         : "backdrop-blur  top-[0rem] bg-main-border  max-w-xl"
     }
    `}
    >
      <div className="flex items-center gap-1">
        <div className="flex items-center justify-center -space-x-3">
          <span className="block w-6 h-6 border-2 rounded-full border-main-900 bg-main-300" />
          <span className="block w-8 h-8 border-4 rounded-full border-main-900 bg-main-500" />
        </div>
        <h1 className="font-medium tracking-wide">Tavern</h1>
      </div>
      <ul className="flex items-center gap-5 ml-auto text-white/70">
        <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
          What is Tavern?
        </li>
        <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
          Features
        </li>
        <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
          Pricing
        </li>
      </ul>
    </nav>
  );
};

const Footer = () => {
  return (
    <footer className="flex items-start max-w-4xl mx-auto mb-28">
      <ul className="grid gap-1 max-w-max">
        <div className="flex items-center gap-1 mb-1.5">
          <div className="flex items-center justify-center -space-x-3">
            <span className="block w-6 h-6 border-2 rounded-full border-main-900 bg-main-300" />
            <span className="block w-8 h-8 border-4 rounded-full border-main-900 bg-main-500" />
          </div>
        </div>
        <li className="text-sm font-normal leading-5 text-white/70">
          Built with love from,
        </li>
        <li className="text-sm font-normal leading-5 text-white/70">
          Italia and United
        </li>
        <li className="text-sm font-normal leading-5 text-white/70">Kingdom.</li>
      </ul>

      <div className="flex items-start justify-between w-full max-w-md gap-5 ml-auto">
        <ul className="grid flex-1 gap-1 max-w-max">
          <h1 className="font-medium tracking-wide  mb-1.5">Discover</h1>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Pricing
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Company
          </li>
        </ul>

        <ul className="grid flex-1 gap-1 max-w-max">
          <h1 className="font-medium tracking-wide  mb-1.5">Legal</h1>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Terms of Service
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Privacy Policy
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Cookie Policy
          </li>
        </ul>

        <ul className="grid flex-1 gap-1 max-w-max">
          <h1 className="font-medium tracking-wide  mb-1.5">Our Socials</h1>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Discord
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Twitter
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            Instagram
          </li>
          <li className="text-sm font-normal leading-5 duration-150 hover:cursor-pointer hover:text-white text-white/70">
            LinkedIn
          </li>
        </ul>
      </div>
    </footer>
  );
};
