import Image from "next/image";
import { BsBell, BsPlus } from "react-icons/bs";
import ThreadContribution from "./threadContribution";
import { IoPlay } from "react-icons/io5";
import { AiOutlineShareAlt } from "react-icons/ai";

export default () => {
  return (
    <>
      <div className="fixed top-0 bottom-0 left-0 right-0 w-screen h-screen bg-image blur opacity-5 after:absolute after:content-[''] after:left-0 after:right-0 after:bottom-0 after:top-0 after:bg-main-900/30">
        <img src="/3.jpg" className="object-scale-down" />
      </div>
      <div className="flex gap-8">
        <div className="overflow-hidden max-w-[508px]">
          <img
            src={"/3.jpg"}
            className="block h-auto max-w-full align-middle border rounded-lg drop-shadow-md bg-main-800 border-main-border "
          />
        </div>

        <div className="max-w-[550px] w-full flex flex-col gap-4">
          <h1 className="text-2xl font-medium leading-none text-wide">
            Warcraft S6 Rogue
          </h1>

          <p className="max-w-sm text-sm leading-5 text-white/70">
            Female blood-elf rogue wearing Naxx 10 man gear from the Wrath of the
            Lich King: World of Warcraft by
          </p>

          <ul className="flex gap-3 font-normal leading-none tracking-wide">
            <li className="px-2 py-1 text-xs tracking-wide duration-150 rounded-full text-white/70 bg-main-800">
              #photoshop
            </li>
            <li className="px-2 py-1 text-xs tracking-wide duration-150 rounded-full text-white/70 bg-main-800">
              #warcraft
            </li>
            <li className="px-2 py-1 text-xs tracking-wide duration-150 rounded-full text-white/70 bg-main-800">
              #offline
            </li>
          </ul>
          <div className="flex items-start w-full gap-3 shrink-0">
            <Image
              className="rounded-full ring-1 ring-main-border p-0.5 strink-0"
              height="38"
              width="38"
              src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
              alt="discord user profile picture generated by api"
            />
            <span className="flex flex-col text-sm gap-0.5  strink-0">
              <a className="mt-auto">Finnigan Sham</a>
              <p className="block mb-0.5 text-xs tracking-wide text-left opacity-70">
                1k Followers
              </p>
            </span>
          </div>

          <p className="text-sm leading-5 text-white/70">Contribution Timeline</p>
          <div className="px-4  rounded-md max-w-max mt-0.5 ">
            <ul className="flex flex-col gap-5 pl-8 border-l border-main-border">
              <li className="relative">
                <span className="absolute -left-[2.9rem]  rounded-full border border-main-border text-white/70 bg-main-800 h-[28px] w-[28px] text-sm flex items-center justify-center">
                  <BsBell />
                </span>
                <span className="flex items-center gap-3 shink-0">
                  <Image
                    className="border rounded-full border-main-border bg-main-800 shrink-0"
                    height="28"
                    width="28"
                    src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
                    alt="discord user profile picture generated by api"
                  />
                  <p className="text-xs leading-4 tracking-wide align-middle text-white/70">
                    <span className="text-white/100">John Finnigan</span> created
                    this thread titled{" "}
                    <span className="text-white/100">LoTR Theory</span>{" "}
                  </p>
                </span>
              </li>
              <ThreadContribution type="image" />
              <ThreadContribution type="sound" />
              <ThreadContribution type="text" />
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};
