import Image from "next/image";
import { memo } from "react";
import { AiOutlineSound, AiOutlineMessage, AiOutlinePicture } from "react-icons/ai";

const randomNames = ["saya#3893", "kianrws#rs4", "bellamonnet#9938", "tyasly#9929"];

export default memo((props) => {
  switch (props.type) {
    case "sound":
      return (
        <li className="flex gap-3.5 relative items-center">
          <span className="absolute -left-[2.9rem]  rounded-full border border-main-border text-white/70 bg-main-800 h-[28px] w-[28px] text-sm flex items-center justify-center">
            <AiOutlineSound />
          </span>
          <div className="shrink-0">
            <Image
              className="border rounded-full border-main-border bg-main-800 shrink-0"
              height="28"
              width="28"
              src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
              alt="discord user profile picture generated by api"
            />
          </div>

          <p className="inline text-xs leading-4 tracking-wide text-left text-white/70">
            <span className="text-white">
              {randomNames[Math.floor(Math.random() * randomNames.length)]}
            </span>{" "}
            contributed sound to this thread{" "}
            <a className="inline text-white text-ellipsis"> soundclip.wav</a>
          </p>
        </li>
      );
    case "text":
      return (
        <li className="flex gap-3.5 relative items-center">
          <span className="absolute -left-[2.9rem]  rounded-full border border-main-border text-white/70 bg-main-800 h-[28px] w-[28px] text-sm flex items-center justify-center">
            <AiOutlineMessage />
          </span>
          <div className="shrink-0">
            <Image
              className="border rounded-full border-main-border bg-main-800 shrink-0"
              height="28"
              width="28"
              src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
              alt="discord user profile picture generated by api"
            />
          </div>
          <p className="inline text-xs tracking-wide text-left text-white/70">
            <span className="text-white">
              {" "}
              {randomNames[Math.floor(Math.random() * randomNames.length)]}
            </span>{" "}
            contributed lore to this thread.
          </p>
        </li>
      );
    case "image":
      return (
        <li className="flex gap-3.5 relative items-center">
          <span className="absolute -left-[2.9rem]  rounded-full border border-main-border text-white/70 bg-main-800 h-[28px] w-[28px] text-sm flex items-center justify-center">
            <AiOutlinePicture />
          </span>
          <div className="shrink-0">
            <Image
              className="border rounded-full border-main-border bg-main-800 shrink-0"
              height="28"
              width="28"
              src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
              alt="discord user profile picture generated by api"
            />
          </div>
          <p className="inline text-xs tracking-wide text-left text-white/70">
            <span className="text-white">
              {" "}
              {randomNames[Math.floor(Math.random() * randomNames.length)]}
            </span>{" "}
            contributed visuals to this thread
            <a className="inline text-white text-ellipsis"> image.png</a>
          </p>
        </li>
      );
    default:
      return null;
  }
});
