import Image from "next/image";
import { AiOutlineMessage } from "react-icons/ai";
export default () => {
  return (
    <li className="flex gap-3.5 relative">
      <span className="absolute -left-12 rounded-full border border-sky-900 h-[28px] w-[28px] text-md flex items-center justify-center text-sky-300 bg-sky-900">
        <AiOutlineMessage />
      </span>
      <div className="shrink-0">
        <Image
          className="border rounded-full border-main-border bg-main-800 shrink-0"
          height="28"
          width="28"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
      </div>
      <div className="grid gap-1.5">
        <p className="inline text-xs tracking-wide text-left text-white/70">
          Jay Pacheco left a comment on this thread{" "}
        </p>
        <div className="p-2 mt-0.5 text-sm border rounded-md bg-main-700 border-main-border">
          <p className="text-xs tracking-wide opacity-70">
            Just checking in to see if I can help with your timeless in anyway.
            Please don't hesitate to reach out and love to chat. This is a template
            comment to provide whitespace regularities.
          </p>
        </div>
      </div>
    </li>
  );
};
