import Image from "next/image";
import { BsBell, BsPlus } from "react-icons/bs";
import ThreadContribution from "./threadContribution";
import { IoPlay } from "react-icons/io5";

export default () => {
  return (
    <>
      <div className="flex gap-5">
        <div className="relative overflow-hidden">
          <div className="max-w-[600px] flex flex-col gap-5">
            <div className="relative h-full max-h-[600px] mx-auto my-0 overflow-hidden border rounded-lg drop-shadow-md bg-main-800 border-main-border">
              <img src={"/3.jpg"} className="object-fill w-full" />
            </div>
            <div className="p-2 mt-0.5 text-sm border rounded-md bg-main-800 border-main-border">
              <p className="text-xs tracking-wide opacity-70">
                The Lord of the Rings is an epic high-fantasy novel by English author
                and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as
                a sequel to Tolkien's 1937 children's book The Hobbit, but eventually
                developed into a much larger work.
              </p>
            </div>
            <div className="p-2 mt-0.5 text-sm border rounded-md bg-main-800 border-main-border">
              <div className="flex items-center gap-3.5">
                <span className="block mx-auto my-1 w-max">
                  <span
                    className={`text-white/70 flex relative items-center justify-center hover:cursor-pointer group rounded-full hover:text-white duration-150`}
                  >
                    <span className="text-[1.3rem] relative">
                      <IoPlay />
                      {/* <span className="absolute z-50 px-2 py-1 text-xs tracking-wide text-white duration-150 -translate-x-1/2 rounded-md shadow-md opacity-0 left-1/2 -top-5 bg-main-800 group-hover:opacity-100 group-hover:-top-7">
                        Play
                      </span> */}
                    </span>
                  </span>
                </span>
                <span className="block w-full h-1.5 bg-main-900 rounded-full relative after:absolute after:content-[''] after:w-24 after:rounded-full after:bg-white/70 after:h-full overflow-hidden"></span>
                <span className="block text-xs tracking-wide opacity-70">
                  0:10/1:00
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="w-[600px] py-3">
          <div className="px-5">
            <ul className="flex flex-col gap-6 px-8 border-l border-main-border">
              <li className="relative">
                <span className="absolute -left-[2.9rem]  rounded-full border border-main-border text-white/70 bg-main-800 h-[28px] w-[28px] text-sm flex items-center justify-center">
                  <BsBell />
                </span>
                <span className="flex items-center gap-3 shink-0">
                  <Image
                    className="border rounded-full border-main-border bg-main-800 shrink-0"
                    height="28"
                    width="28"
                    src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
                    alt="discord user profile picture generated by api"
                  />
                  <p className="text-xs leading-none tracking-wide align-middle text-white/70">
                    <span className="text-white/100">John Finnigan</span> created
                    this thread titled{" "}
                    <span className="text-white/100">LoTR Theory</span>{" "}
                    <span className="inline-block w-1 h-1 my-auto bg-white/70 rounded-full mx-1.5 mb-0.5" />{" "}
                    2 days ago
                  </p>
                </span>
              </li>
              <ThreadContribution type="image" />
              <ThreadContribution type="sound" />
              <ThreadContribution type="text" />
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};
