import React from "react";
import { useRef, useEffect } from "react";
import { sleep } from "../static/util";
import Image from "next/image";
import { AiOutlineClose } from "react-icons/ai";

export default ({ show, setShow }) => {
  const container = useRef(null);

  useEffect(() => {
    (async () => {
      if (show) {
        await sleep(1);
        container?.current?.childNodes[0]?.classList?.remove("opacity-0");
        container?.current?.childNodes[0]?.classList?.remove("-translate-y-8");
      }
    })();
  }, [show, container]);

  async function handleClose() {
    container?.current?.childNodes[0]?.classList?.add("opacity-0");
    container?.current?.childNodes[0]?.classList?.add("-translate-y-8");
    await sleep(300);
    setShow(false);
  }

  return (
    show && (
      <div
        className="fixed top-0 left-0 flex items-center justify-center w-full h-full transition-all duration-150 z-100 bg-main-900/90"
        ref={container}
      >
        <div className="duration-300 -translate-y-8 border rounded-lg opacity-0 border-main-border bg-main-800 main">
          <div className="max-w-[550px] w-full min-w-[550px] pb-5 relative">
            <button
              className="absolute items-center justify-center -right-3.5 top-5 rounded-full border border-main-border bg-main-900 h-[28px] w-[28px] flex"
              onClick={handleClose}
            >
              <AiOutlineClose className="text-xs opacity-70" />
            </button>
            <div className="flex items-center border-b border-main-border">
              <ul className="flex h-full gap-5 px-5">
                <li className="py-5 flex text-sm gap-1.5 after:absolute after:content-[''] after:bottom-[-1px] after:h-[2px] after:block after:bg-green-900 relative after:w-full">
                  <span className="text-green-400">Notifications</span>
                  <span className="h-[20px] w-[24px] border-green-900 border bg-green-900/40 text-green-400 text-center font-semibold rounded-md tracking-tighter flex items-center justify-center">
                    3
                  </span>
                </li>
                <li className="py-5  flex text-sm gap-1.5 after:absolute after:content-[''] after:block after:bg-main-border relative after:w-full">
                  <span className=" text-white/70">Contributions</span>
                  <span className="h-[20px] w-[24px] border-main-border  border text-white/70 rounded-md bg-main-700 text-center font-semibold  tracking-tighter flex items-center justify-center">
                    3
                  </span>
                </li>
              </ul>
            </div>

            <ul className="grid">
              <CommentItem />
              {/* <NotificationItem comment={true} /> */}
              {/* <NotificationItem /> */}
              {/* <ContributionItem /> */}
              {/* <NotificationItem comment={true} /> */}
              {/* <ContributionItem /> */}
            </ul>
          </div>
        </div>
      </div>
    )
  );
};

const CommentItem = (props) => {
  return (
    <li className="flex gap-3.5 p-5 border-b border-main-border">
      <div className="shrink-0">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
      </div>
      <div className="grid gap-1.5">
        <p className="inline-flex text-xs tracking-wide text-left text-white/70">
          Jay Pacheco commented on your post{" "}
          <a className="ml-1 text-green-400 text-ellipsis"> Arthas Menethil</a>
        </p>
        <p className="inline-flex text-xs tracking-wide text-left text-white/70">
          2h Ago — Comment Preview
        </p>
        <div className="p-3 mt-0.5 text-sm border rounded-md bg-main-700 border-main-border">
          <p className="text-xs tracking-wide opacity-70">
            Amazing art, is this the first draft? Feel free to take a look at a piece
            I've made and tell me what you think...
          </p>
        </div>
      </div>
    </li>
  );
};

const NotificationItem = (props) => {
  return (
    <li className="flex items-start w-full gap-3 py-5 ml-auto border-b px-7 border-main-border">
      <Image
        className="rounded-full ring-1 ring-main-border p-0.5"
        height="38"
        width="38"
        src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
        alt="discord user profile picture generated by api"
      />
      <span className="flex flex-col w-full text-sm text-left">
        <span className="flex">
          <a>dian#4192</a>
          <p className="ml-auto text-xs tracking-wide text-left opacity-40">
            53 min ago
          </p>
        </span>
        <p className="flex text-xs tracking-wide text-left text-white/70 whitespace-nowrap max-w-[230px]">
          {props.comment ? "Commented on " : "Liked "}
          your post{" "}
          <a className="text-green-400 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
            {" "}
            Arthas Menethil
          </a>
        </p>
      </span>
    </li>
  );
};

const ContributionItem = () => {
  return (
    <li className="flex flex-col items-center w-full gap-2 p-5 ml-auto border-b border-main-border">
      <div className="flex items-start gap-3">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
        <span className="inline-block w-full text-sm text-left ">
          <span className="flex">
            <a>dian#4192</a>
            <p className="ml-auto text-xs tracking-wide text-left opacity-40">
              53 min ago
            </p>
          </span>
          <p className="inline-block text-xs tracking-wide text-left text-white/70">
            has requested to contribute to your post{" "}
            <a className="text-green-400 max-w-[175px] overflow-hidden text-ellipsis whitespace-nowrap inline-block align-middle">
              Illidan Stormrage the Betrayer
            </a>
          </p>
        </span>
      </div>
      <div className="w-full pb-0.5 border-main-border max-w-[200px] items-start mr-auto ml-12">
        <div className="flex gap-3.5">
          <button className="flex-1 px-1.5 min-h-[30px] text-sm text-white/70 border rounded-md bg-main-700 border-main-border  hover:bg-main-900 hover:text-white duration-150">
            Deny
          </button>
          <button className="flex-1 px-1.5 min-h-[30px] text-sm  border border-green-900 rounded-md text-green-400 bg-green-900/40 duration-150 hover:bg-green-900">
            Approve
          </button>
        </div>
      </div>
    </li>
  );
};
