import React from "react";
import { AiOutlineFileAdd } from "react-icons/ai";
import { useRef, useEffect } from "react";
import { sleep } from "../static/util";
import Image from "next/image";

export default ({ show, setShow }) => {
  const container = useRef(null);

  useEffect(() => {
    (async () => {
      if (show) {
        await sleep(1);
        container?.current?.childNodes[0]?.classList?.remove("opacity-0");
        container?.current?.childNodes[0]?.classList?.remove("-translate-y-8");
      }
    })();
  }, [show, container]);

  async function handleClose() {
    container?.current?.childNodes[0]?.classList?.add("opacity-0");
    container?.current?.childNodes[0]?.classList?.add("-translate-y-8");
    await sleep(300);
    setShow(false);
  }

  return (
    show && (
      <div
        className="fixed top-0 left-0 flex items-center justify-center w-full h-full transition-all duration-150 z-100 bg-main-900/90"
        ref={container}
      >
        <div className="duration-300 -translate-y-8 border rounded-lg opacity-0 border-main-border bg-main-800 main">
          <div className="min-w-[500px] py-5">
            <p className="px-5 text-xl">Notifications and Contributions</p>
            <p className="px-5 text-xs tracking-wide opacity-70">
              Set a title that people can use to search for your thread.
            </p>
            <ul className="grid">
              <NotificationItem comment={true} />
              <NotificationItem />
              <ContributionItem />
              <NotificationItem comment={true} />
              <ContributionItem />
            </ul>
          </div>
        </div>
      </div>
    )
  );
};

const NotificationItem = (props) => {
  return (
    <li className="flex items-start w-full gap-3 px-3 py-3 ml-auto border-b border-main-border">
      <Image
        className="rounded-full ring-1 ring-main-border p-0.5"
        height="38"
        width="38"
        src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
        alt="discord user profile picture generated by api"
      />
      <span className="flex flex-col w-full text-sm text-left">
        <span className="flex">
          <a>dian#4192</a>
          <p className="ml-auto text-xs tracking-wide text-left opacity-40">
            53 min ago
          </p>
        </span>
        <p className="flex text-xs tracking-wide text-left text-white/70 whitespace-nowrap max-w-[230px]">
          {props.comment ? "Commented on " : "Liked "}
          your post{" "}
          <a className="text-green-400 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
            {" "}
            Arthas Menethil
          </a>
        </p>
      </span>
    </li>
  );
};

const ContributionItem = () => {
  return (
    <li className="flex flex-col items-center w-full gap-2 px-3 py-3 ml-auto border-b border-main-border">
      <div className="flex items-start gap-3">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
        <span className="inline-block w-full text-sm text-left ">
          <span className="flex">
            <a>dian#4192</a>
            <p className="ml-auto text-xs tracking-wide text-left opacity-40">
              53 min ago
            </p>
          </span>
          <p className="inline-block text-xs tracking-wide text-left text-white/70">
            has requested to contribute to your post{" "}
            <a className="text-green-400 max-w-[175px] overflow-hidden text-ellipsis whitespace-nowrap inline-block align-middle">
              Illidan Stormrage the Betrayer
            </a>
          </p>
        </span>
      </div>
      <div className="w-full pb-0.5 border-main-border max-w-[200px] items-start mr-auto ml-12">
        <div className="flex gap-3.5">
          <button className="flex-1 px-1.5 min-h-[30px] text-sm text-white/70 border rounded-md bg-main-700 border-main-border  hover:bg-main-900 hover:text-white duration-150">
            Deny
          </button>
          <button className="flex-1 px-1.5 min-h-[30px] text-sm  border border-green-900 rounded-md text-green-400 bg-green-900/40 duration-150 hover:bg-green-900">
            Approve
          </button>
        </div>
      </div>
    </li>
  );
};
