import Image from "next/image";
import Wrap from "../components/wrap";
export default () => {
  return (
    <div className="overflow-hidden border rounded-lg bg-main-800 border-main-border">
      <li className="flex px-3 py-3 text-sm bg-transparent border-b border-main-border ">
        Notifications & Contributions
      </li>
      <ul className="grid">
        <NotificationItem comment={true} />
        <NotificationItem />
        <ContributionItem />
        <NotificationItem comment={true} />
        <ContributionItem />
      </ul>
      <div className="px-5 py-3">
        <span className="relative flex items-center justify-center w-full gap-2 text-xs tracking-wide text-center duration-150 opacity-70 hover:opacity-100 hover:cursor-pointer">
          <span>See more...</span>
        </span>
      </div>
    </div>
  );
};

const NotificationItem = (props) => {
  return (
    <li className="flex items-start w-full gap-3 px-3 py-3 ml-auto border-b border-main-border">
      <Image
        className="rounded-full ring-1 ring-main-border p-0.5"
        height="38"
        width="38"
        src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
        alt="discord user profile picture generated by api"
      />
      <span className="flex flex-col w-full text-sm text-left">
        <span className="flex">
          <a>dian#4192</a>
          <p className="ml-auto text-xs tracking-wide text-left opacity-40">
            53 min ago
          </p>
        </span>
        <p className="flex text-xs tracking-wide text-left text-white/70 whitespace-nowrap max-w-[230px]">
          {props.comment ? "Commented on " : "Liked "}
          your post{" "}
          <a className="text-green-400 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
            {" "}
            Arthas Menethil
          </a>
        </p>
      </span>
    </li>
  );
};

const ContributionItem = () => {
  return (
    <li className="flex flex-col items-center w-full gap-2 px-3 py-3 ml-auto border-b border-main-border">
      <div className="flex items-start gap-3">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
        <span className="inline-block w-full text-sm text-left ">
          <span className="flex">
            <a>dian#4192</a>
            <p className="ml-auto text-xs tracking-wide text-left opacity-40">
              53 min ago
            </p>
          </span>
          <p className="inline-block text-xs tracking-wide text-left text-white/70">
            has requested to contribute to your post{" "}
            <a className="text-green-400 max-w-[175px] overflow-hidden text-ellipsis whitespace-nowrap inline-block align-middle">
              Illidan Stormrage the Betrayer
            </a>
          </p>
        </span>
      </div>
      <div className="w-full pb-0.5 pl-12 ml-auto border-main-border">
        <div className="flex gap-3.5">
          <button className="flex-1 px-1.5 min-h-[26px] text-sm text-white/70 border rounded-md bg-main-700 border-main-border  hover:bg-main-900 hover:text-white duration-150">
            Deny
          </button>
          <button className="flex-1 px-1.5 min-h-[26px] text-sm  border border-green-900 rounded-md text-green-400 bg-green-900/40 duration-150 hover:bg-green-900">
            Approve
          </button>
        </div>
      </div>
    </li>
  );
};
