import Image from "next/image";
import Wrap from "../components/wrap";
export default () => {
  return (
    <div className="overflow-hidden border rounded-lg bg-main-800 border-main-border">
      {/* <div className="w-full border-b border-main-border">
        <ul className="flex gap-3 px-5 py-3 text-sm rounded-md">
          <li className="flex gap-1.5 text-white relative">Your Notifications</li>
        </ul>
      </div> */}
      <li className="flex px-5 py-3 text-sm bg-transparent border-b border-main-border ">
        Your notifications and contributions
      </li>
      <ul className="grid gap-1 pt-2">
        <li className="flex items-center w-full gap-3 px-5 pt-1 pb-2 ml-auto border-b border-main-border">
          <Image
            className="rounded-full ring-1 ring-main-border p-0.5"
            height="38"
            width="38"
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="flex flex-col w-full text-sm text-left">
            <span className="flex">
              <a>kian#1118</a>
              <p className="ml-auto text-xs tracking-wide text-left opacity-70">
                43 min ago
              </p>
            </span>
            <p className="flex text-xs tracking-wide text-left opacity-70 whitespace-nowrap max-w-[230px]">
              Liked your post{" "}
              <a className="text-cyan-300 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
                {" "}
                C'thun WoW fanart
              </a>
            </p>
          </span>
        </li>
        <li className="flex items-center w-full gap-3 px-5 pt-1 pb-2 ml-auto border-b border-main-border">
          <Image
            className="rounded-full ring-1 ring-main-border p-0.5"
            height="38"
            width="38"
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="flex flex-col w-full text-sm text-left">
            <span className="flex">
              <a>tyler#1211</a>
              <p className="ml-auto text-xs tracking-wide text-left opacity-70">
                5 min ago
              </p>
            </span>
            <p className="flex text-xs tracking-wide text-left opacity-70 whitespace-nowrap max-w-[230px]">
              Commented on your post{" "}
              <a className="text-cyan-300 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
                {" "}
                Kel'thuzad Hearthstone 1111
              </a>
            </p>
          </span>
        </li>
        <li className="flex items-center w-full gap-3 px-5 pt-1 pb-2 ml-auto border-b border-main-border">
          <Image
            className="rounded-full ring-1 ring-main-border p-0.5"
            height="38"
            width="38"
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="flex flex-col w-full text-sm text-left">
            <span className="flex">
              <a>shaun#7712</a>
              <p className="ml-auto text-xs tracking-wide text-left opacity-70">
                8 min ago
              </p>
            </span>
            <p className="flex text-xs tracking-wide text-left opacity-70 whitespace-nowrap max-w-[230px]">
              Liked your post{" "}
              <a className="text-cyan-300 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
                {" "}
                Sova x Reyna x Cypher
              </a>
            </p>
          </span>
        </li>
        <li className="flex items-center w-full gap-3 px-5 pt-1 pb-2 ml-auto border-b border-main-border">
          <Image
            className="rounded-full ring-1 ring-main-border p-0.5"
            height="38"
            width="38"
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="flex flex-col w-full text-sm text-left">
            <span className="flex">
              <a>dian#4192</a>
              <p className="ml-auto text-xs tracking-wide text-left opacity-70">
                53 min ago
              </p>
            </span>
            <p className="flex text-xs tracking-wide text-left opacity-70 whitespace-nowrap max-w-[230px]">
              Commented on your post{" "}
              <a className="text-cyan-300 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
                {" "}
                Arthas Menethil
              </a>
            </p>
          </span>
        </li>
        <li className="flex items-center w-full gap-3 px-5 pt-1 pb-2 ml-auto">
          <Image
            className="rounded-full ring-1 ring-main-border p-0.5"
            height="38"
            width="38"
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="flex flex-col w-full text-sm text-left">
            <span className="flex">
              <a>hahn#blki</a>
              <p className="ml-auto text-xs tracking-wide text-left opacity-70">
                16 min ago
              </p>
            </span>
            <p className="flex text-xs tracking-wide text-left opacity-70 whitespace-nowrap max-w-[230px]">
              Liked your post{" "}
              <a className="text-cyan-300 text-ellipsis whitespace-nowrap max-w-[144px] block overflow-hidden ml-1">
                {" "}
                C'thun WoW fanart
              </a>
            </p>
          </span>
        </li>
      </ul>
      <div className="px-5 py-3 border-t border-main-border">
        <span className="relative flex items-center justify-center w-full gap-2 text-xs tracking-wide text-center opacity-70">
          <span>See more...</span>
        </span>
      </div>
    </div>
  );
};
