import Image from "next/image";
import { AiOutlineFileAdd } from "react-icons/ai";
import { BsBell } from "react-icons/bs";

export default ({ user }) => {
  return (
    <div className="fixed flex p-4 border-b border-main-700 bg-main-800 w-[calc(100%-275px)] right-0">
      <ul className="flex max-w-max border rounded-md bg-main-700 border-main-600 max-h-[38px] min-h-[38px] items-center">
        <li className="flex px-3 py-1 mx-1 rounded-md bg-main-600">
          <span className="text-sm font-medium opacity-100">Explore</span>
        </li>
        <li className="flex px-3 py-1 mx-1 rounded-md bg-main-700">
          <span className="text-sm font-normal opacity-70">Community feed</span>
        </li>
        <li className="flex px-3 py-1 mx-1 rounded-md bg-main-700">
          <span className="text-sm font-normal opacity-70">Mutual friends</span>
        </li>
      </ul>

      <div className="ml-auto">
        {user && (
          <aside className="flex items-center gap-3 ml-auto">
            <span>
              <h5 className="tracking-wide text-sm mb-0.5 text-right">
                {user.me.username}#{user.me.discriminator}
              </h5>
              <p className="text-xs tracking-wide opacity-70">{user.me.email}</p>
            </span>
            <Image
              className="rounded-full ring-1 ring-main-600 p-0.5"
              height="38"
              width="38"
              src={`https://cdn.discordapp.com/avatars/${user.me.id}/${user.me.avatar}.png`}
              alt="discord user profile picture generated by api"
            />
            <span className="h-[38px] w-[38px] bg-main-700 border-main-600 border rounded-full flex items-center justify-center">
              <BsBell className="text-xl shrink-0 opacity-70" />
            </span>
            <span className="h-[38px] w-[38px] bg-main-700 border-main-600 border rounded-full flex items-center justify-center">
              <BsBell className="text-xl shrink-0 opacity-70" />
            </span>
            <span className="h-[38px] w-[38px] bg-main-700 border-main-600 border rounded-full flex items-center justify-center">
              <BsBell className="text-xl shrink-0 opacity-70" />
            </span>
          </aside>
        )}
      </div>
    </div>
  );
};
