import Wrap from "./wrap";
import Image from "next/image";
export default () => {
  return (
    <Wrap>
      <li className="flex text-sm bg-transparent border border-transparent rounded-md">
        Recommended to follow
      </li>
      <ul className="grid gap-3 mt-3">
        <li className="flex items-start gap-2 text-sm">
          <Image
            className=" border border-main-700 rounded-full drop-shadow-sm p-0.5 shrink-0 grow-0 mt-auto"
            height="38"
            width="38"
            quality={100}
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="grid">
            <a>Svk</a>
            <p className="text-xs tracking-wide opacity-70">@swkn#dev</p>
          </span>
        </li>
        <li className="flex items-start gap-2 text-sm">
          <Image
            className=" border border-main-700 rounded-full drop-shadow-sm p-0.5 shrink-0 grow-0 mt-auto"
            height="38"
            width="38"
            quality={100}
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="grid">
            <a>Svk</a>
            <p className="text-xs tracking-wide opacity-70">@swkn#dev</p>
          </span>
        </li>
        <li className="flex items-start gap-2 text-sm">
          <Image
            className=" border border-main-700 rounded-full drop-shadow-sm p-0.5 shrink-0 grow-0 mt-auto"
            height="38"
            width="38"
            quality={100}
            src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
            alt="discord user profile picture generated by api"
          />
          <span className="grid">
            <a>Svk</a>
            <p className="text-xs tracking-wide opacity-70">@swkn#dev</p>
          </span>
        </li>
      </ul>
    </Wrap>
  );
};
