import Image from "next/image";
export const CommentItem = (props) => {
  return (
    <li className="flex gap-3.5 p-5 border-b border-main-border">
      <div className="shrink-0">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
      </div>
      <div className="grid gap-1.5">
        <p className="inline text-xs tracking-wide text-left text-white/70">
          Jay Pacheco commented on your post{" "}
          <a className="text-green-400 text-ellipsis"> Arthas Menethil</a>
        </p>
        <p className="inline-flex text-xs tracking-wide text-left text-white/70">
          2h Ago — Comment Preview
        </p>
        <div className="p-3 mt-0.5 text-sm border rounded-md bg-main-700 border-main-border">
          <p className="text-xs tracking-wide opacity-70">
            Amazing art, is this the first draft? Feel free to take a look at a piece
            I've made and tell me what you think...
          </p>
        </div>
      </div>
    </li>
  );
};
