import Image from "next/image";
export const ContributionItem = (props) => {
  return (
    <li className="flex gap-3.5 p-5 border-t border-main-border">
      <div className="shrink-0">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://cdn.discordapp.com/avatars/1012899721477619862/0ea94e9083dea503c92e8f562060d81d.webp`}
          alt="discord user profile picture generated by api"
        />
      </div>
      <div className="grid gap-1.5">
        <p className="inline text-xs tracking-wide text-left text-white/70">
          <span className="inline">
            Jay Pacheco contributed a "TYPE" on your post
          </span>
          <a className="inline text-green-400 text-ellipsis"> Arthas Menethil</a>{" "}
        </p>
        <p className="inline-flex text-xs tracking-wide text-left text-white/70">
          2h Ago — Approve or Deny
        </p>

        <div className="flex gap-2.5 mt-0.5">
          <button className="px-2 min-h-[30px] text-sm  border border-green-900 rounded-md text-green-400 bg-green-900/40 duration-150 hover:bg-green-900">
            Approve
          </button>
          <button className="px-2 min-h-[30px] text-sm text-white/70 border rounded-md bg-main-700 border-main-border  hover:bg-main-900 hover:text-white duration-150">
            Deny
          </button>
        </div>
      </div>
    </li>
  );
};
