import React, { useRef, useState, useEffect } from "react";
import { AiOutlineSetting } from "react-icons/ai";
import { IoMdCheckmark } from "react-icons/io";
import { CommentItem } from "./commentItem";
import { LikeItem } from "./likeItem";
import Image from "next/image";
import { ContributionItem } from "./contributionItem";
const Notis = () => {
  const slideContainer = useRef(null);
  const [activeSlide, setActiveSlide] = useState(0);
  const STATIC_OPTS = [
    { name: "Unread" },
    { name: "Following" },
    { name: "Archived" },
  ];

  useEffect(() => {
    const childNodes = [...slideContainer.current.childNodes].slice(1);
    const activeChildNode = childNodes[activeSlide];
    const { width, height } = activeChildNode.getBoundingClientRect();
    const lavaLamp = slideContainer.current.childNodes[0];
    lavaLamp.style.width = `${width}px`;
    lavaLamp.style.height = `${height}px`;
    lavaLamp.style.left = `${activeChildNode.offsetLeft}px`;
  }, [activeSlide]);

  return (
    <>
      <div className="flex flex-col border-b border-main-border">
        <div className="flex items-center justify-center px-5 py-4">
          <div className="flex items-center w-full mr-auto">
            <h1 className="mr-auto text-xl font-medium tracking-wide">
              Notifications
            </h1>
            <span className="items-center flex ml-auto text-xs text-green-400 gap-1.5  hover:cursor-pointer">
              <IoMdCheckmark className="text-base" />
              Mark all as read
            </span>
          </div>
        </div>
        <ul
          ref={slideContainer}
          className="relative flex gap-5 px-5 py-4 text-sm leading-5 border-t text-white/70 border-main-border"
        >
          <span
            className={`will-change-transform block w-full absolute bottom-0 z-10 font-normal bg-white rounded-md  max-h-[1px] left-0.5 duration-150 ease-[cubic-bezier(.17,.67,.83,.67)] transition-[left]`}
          />
          {STATIC_OPTS.map((_, i) => (
            <li
              key={i}
              onClick={() => {
                setActiveSlide(i);
              }}
              className={`${
                activeSlide === i && "text-white"
              } flex gap-2.5 items-center max-w-max hover:cursor-pointer duration-75`}
            >
              {_.name}
              <span
                className={`${
                  activeSlide === i
                    ? "bg-white text-black"
                    : "bg-white/70 text-black"
                } flex items-center w-full h-5 px-1 text-xs font-semibold rounded-md max-w-max duration-75`}
              >
                108
              </span>
            </li>
          ))}
          <li className="flex ml-auto text-white/70">
            <AiOutlineSetting className="text-[1.3rem]" />{" "}
          </li>
        </ul>
      </div>
      {/* <CommentItem />
      <LikeItem />
      <ContributionItem /> */}

      <div className="flex items-start w-full gap-2.5 p-5 border-b border-main-border">
        <Image
          className="rounded-full ring-1 ring-main-border p-0.5"
          height="38"
          width="38"
          src={`https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 50)}`}
          alt="discord user profile picture generated by api"
        />
        <div className="flex flex-col text-sm text-white/70 gap-1.5">
          <p className="inline-block">
            <span className="inline-block mr-1 font-medium text-white">
              Synapois#1983
            </span>
            requested to commit a file <br />
            <span className="inline-block font-medium text-green-400">
              Astro Illustration
            </span>{" "}
            to{" "}
            <span className="inline-block font-medium text-green-400">
              Arthus...
            </span>
          </p>
          <p className="inline-flex items-center text-xs text-left text-white/40 ">
            2 hours ago{" "}
            <span className="block w-1 h-1 mx-2 rounded-full bg-white/40" />{" "}
            <a className="inline text-ellipsis">Action Required</a>
          </p>
          <div className="flex gap-2.5 mt-0.5">
            <button className="px-6 min-h-[32px] max-w-[120px] w-full text-sm border border-green-900 rounded-md text-green-400 bg-green-900/40 duration-150 hover:border-green-400">
              Approve
            </button>
            <button className="px-6 min-h-[32px] max-w-[120px] w-full text-sm text-white/70 border rounded-md bg-main-700 border-main-border  hover:border-white/70 duration-150">
              Deny
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Notis;
